# Generated by Django 5.2.17 on 2026-09-21 18:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(max_length=90, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='BlogTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(max_length=60, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_title', models.CharField(blank=True, max_length=70)),
                ('meta_description', models.CharField(blank=True, max_length=160)),
                ('focus_keyword', models.CharField(blank=True, max_length=100)),
                ('canonical_url', models.URLField(blank=True)),
                ('og_title', models.CharField(blank=True, max_length=100)),
                ('og_description', models.CharField(blank=True, max_length=200)),
                ('og_image', models.ImageField(blank=True, upload_to='seo/')),
                ('title', models.CharField(max_length=160)),
                ('slug', models.SlugField(max_length=180, unique=True)),
                ('excerpt', models.TextField(blank=True)),
                ('content', models.TextField()),
                ('hero_image', models.ImageField(blank=True, upload_to='pages/')),
                ('is_published', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_title', models.CharField(blank=True, max_length=70)),
                ('meta_description', models.CharField(blank=True, max_length=160)),
                ('focus_keyword', models.CharField(blank=True, max_length=100)),
                ('canonical_url', models.URLField(blank=True)),
                ('og_title', models.CharField(blank=True, max_length=100)),
                ('og_description', models.CharField(blank=True, max_length=200)),
                ('og_image', models.ImageField(blank=True, upload_to='seo/')),
                ('title', models.CharField(max_length=180)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('excerpt', models.TextField(max_length=320)),
                ('content', models.TextField()),
                ('featured_image', models.ImageField(blank=True, upload_to='blog/')),
                ('image_alt', models.CharField(blank=True, max_length=160)),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
                ('categories', models.ManyToManyField(blank=True, related_name='posts', to='studio.blogcategory')),
                ('related_posts', models.ManyToManyField(blank=True, to='studio.blogpost')),
                ('tags', models.ManyToManyField(blank=True, related_name='posts', to='studio.blogtag')),
            ],
            options={
                'ordering': ['-published_at'],
                'indexes': [models.Index(fields=['is_published', '-published_at'], name='studio_blog_is_publ_a22fa2_idx'), models.Index(fields=['slug'], name='studio_blog_slug_fca3bc_idx')],
            },
        ),
    ]
